### ISSUE TITLE
Starfax (Project 3)- Sarah, Lyndsey, & Matt

### ISSUE THREAD

**Issue by mkernsNCR** [ga-dc/wdi8-project3-gallery#2]
Link to repo: https://github.com/mkernsNCR/Project_3.github.io
Link to deployed app: https://starfax.herokuapp.com/constellations#/

Things you'd like specific feedback on: Our use of factories, JSON seed file, and how DRY our code is.

**Comment by RobertAKARobin** [comment]
# Project 3 Evaluation

[Inline code comments](https://github.com/mkernsNCR/Project_3.github.io/pull/1)

## Back-end Technology

**2: Performing**

> Includes 2 models

## Front-end Technology

**1: Progressing** 

> Basic front-end with at least 1 Angular controller

## Code Quality

**2: Performing**

> Code is well-formatted, well-named, and contains few style / quality issues

## Deployment and Functionality

**2: Performing**

> Application contains no major errors, is deployed correctly, and contains a custom Heroku app name appropriate for the app.

## Planning / Process / Submission

**1: Progressing**

> App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality and link to deployed application

## Comments

Great job, guys! This is a cool-looking app! Your code is very DRY, your seeds are fine, and all your Angular is used exactly correctly.

I deducted points for planning because it looks like you sketched out some ideas but didn't finish writing out your bronze / silver / gold levels, and your main `readme.md` contains little. I would like to have seen you revisit your planning documents as the week progressed. Revisiting documentation is a great way to get un-stuck.

Also, while your code looks great, there's no CUD functionality -- only R.

I'd encourage you to keep working on this! I think a constellation database like this would be really cool, and people would enjoy using it.
