### ISSUE TITLE
OptiRoute

### ISSUE THREAD

**Issue by Ceisen9** [ga-dc/wdi8-project3-gallery#7]
Link to repo: https://github.com/Ceisen9/optiroute
Link to deployed app: http://johnblakeman.com:7777/#/

Things you'd like specific feedback on: 
Optimization so that our controllers do not need to make so many database queries.
How to better separate concerns and advice to DRY up some our functions/forms.

**Comment by joe-gz** [comment]
Awesome job guys! This is a really strong project, and one which you should be happy to show off to potential employers.  
With regards to your comments above, I think you have already done a great job separating concerns for the most part.  I think the next step is to start shifting some elements to costum directives instead of the fat controllers.
I've added some in line comments, as well as provided the full feedback rubric in the below PR.  Let me know if you have any questions!

https://github.com/Ceisen9/optiroute/pull/40/files
